### ISSUE TITLE
Docs & Error: Unknown argument: config

### ISSUE THREAD

**Issue by jere-co** [rh389/codegen-prismic-fetch#3]
### Issue

I'm new to `graphql-codegen` so most likely just doing something wrong, but when running:

```
graphql-codegen --config ./codegen.yml
```

I get the following error: 

```
$ graphql-codegen --config ./codegen.yml
Error: Unknown argument: config
```

My `codegen.yml` contents are as follows:
```
schema:
  https://<my-prismic-repository>.cdn.prismic.io/graphql:
    customFetch: "codegen-prismic-fetch"
generates:
  ./src/types.d.ts:
    plugins:
      - typescript
```

### Docs 

While the README of this repo provides information on how to extend on top of `graphql-codegen` usage, I believe it would make it much easier for people to jump on using this if the docs would go through the whole basic implementation with Prismic & graphql-codegen rather than assuming some prior knowledge.
